# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='topic',
            new_name='blogpost',
        ),
    ]
