# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20160906_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blogpost',
            new_name='topic',
        ),
    ]
